config/routes.rb
Codeapp::Application.routes.draw do
	match "girls/girl_add"=>"girls#girl_add"
	match "girls/girl_edit"=>"girls#girl_edit"
	match "girls/girl_delete"=>"girls#girl_delete"
	match "girls/girl_search"=>"girls#girl_search"
	match "upload/uploadin"=>"upload#uploadin"
	match "upload/uploadout"=>"upload#uploadout"
	match "upload/upload"=>"upload#upload"
	match "boys/add_tree"=>"boys#add_tree"
	match "boys/delete_tree"=>"boys#delete_tree"
	match "boys/edit_tree"=>"boys#edit_tree"
	match "boys/all_delete"=>"boys#all_delete"
	match "code/ajax"=>"code#ajax"
	match "code/list"=>"code#list"
	match "manager/all"=>"manager#all"
  resources :girls
 
  post "girls/try"=>'girls#try'
  get "users/new"
  
  resources :boys

   match ':controller(/:action(/:id))(.:format)'
end

app/models/boy.rb
class Boy < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/boys_controller.rb
class BoysController < ApplicationController
  # GET /boys
  # GET /boys.json
  
  def add_tree     
    if Code.find_by_name(params[:name])
      flag = false
    else
      flag = true
    end
    if flag
      Code.create(:name=>params[:name],:parent_id=>params[:parent_id])
    end
    respond_to do |format|
			  format.json { render :json => {:success=>flag} }
    end  
  end

  def edit_tree
      @code=Code.find(params[:id])
      @code.update_attributes(:name=>params[:name])
    respond_to do |format|
			  format.json { render :json => {:success=>true} }
    end
  end

  def delete_tree  
    @codes=Code.all
    flags=true
    @codes.each do |node|                                          
    if params[:id].to_i == node.parent_id
    flags=false   
    end
    end 
    if flags
    Code.destroy(params[:id])
    end
    respond_to do |format|
			format.json { render :json => {:success=>flags} }
    end
  end
  
  def all_delete
   @codes = Code.all
   respond_to do |format|
			format.js
		end
  end
  
  def index
    @boys = Boy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boys }
    end
  end

  # GET /boys/1
  # GET /boys/1.json
  def show
    @boy = Boy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @boy }
    end
  end

  # GET /boys/new
  # GET /boys/new.json
  def new
    @boy = Boy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @boy }
      format.js
    end
  end

  # GET /boys/1/edit
  def edit
    @boy = Boy.find(params[:id])
  end

  # POST /boys
  # POST /boys.json
  def create
    @boy = Boy.new(params[:boy])

    respond_to do |format|
      if @boy.save
        format.html { redirect_to @boy, notice: 'Boy was successfully created.' }
        format.json { render json: @boy, status: :created, location: @boy }
      else
        format.html { render action: "new" }
        format.json { render json: @boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boys/1
  # PUT /boys/1.json
  def update
    @boy = Boy.find(params[:id])

    respond_to do |format|
      if @boy.update_attributes(params[:boy])
        format.html { redirect_to @boy, notice: 'Boy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boys/1
  # DELETE /boys/1.json
  def destroy
    @boy = Boy.find(params[:id])
    @boy.destroy

    respond_to do |format|
      format.html { redirect_to boys_url }
      format.json { head :no_content }
    end
  end
end

app/views/boys/_form.html.erb
<%= form_for(@boy) do |f| %>
  <% if @boy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boy.errors.count, "error") %> prohibited this boy from being saved:</h2>

      <ul>
      <% @boy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boys/all_delete.js.erb
var node_selected = tree_panel.getSelectionModel().getSelection()
var flag=true
<% @codes.each do |node|%>                                         
    if node_selected[0].data.id==<%=node.parent_id%>
    flag=false   
    end
<% end %>
if(flag){
     Ext.Ajax.request({
       url: 'boys/delete_tree',
       success: function(response){
               tree_panel.remove(node_selected[0].data.id)
       },
       failure: function(response){
            show_tip_message("failure!")
      },
      params: {
          id: node_selected[0].data.id
      }
   })
}else{
     show_tip_message("have dir")
}

app/views/boys/edit.html.erb
<h1>Editing boy</h1>

<%= render 'form' %>

<%= link_to 'Show', @boy %> |
<%= link_to 'Back', boys_path %>

app/views/boys/index.html.erb
<div id="search-panel">
</div>

app/views/boys/index1.html.erb
 <div id="west" class="x-hide-display">
        <p>Hi. I'm the west panel.</p>
    </div>
   <li id="hello" class="left-menu">
    <a href="boys/new">
      <div class="menu-icon"><%= image_tag("shortcuts_11.png") %></div>
      <div class="menu-text">fa</div>
    </a>
    <a href="manage/customer">
      <div class="menu-icon"><%= image_tag("shortcuts_12.png") %></div>
      <div class="menu-text">ma</div>
    </a>
    </li>
    <div id="center2" class="x-hide-display">
        <a id="hideit" href="#">Toggle the west region</a>
        <p>My closable attribute is set to false so you can't close me. The other center panels can be closed.</p>
        <p>The center panel automatically grows to fit the remaining space in the container that isn't taken up by the border regions.</p>
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed metus nibh, sodales a, porta at, vulputate eget, dui. Pellentesque ut nisl. Maecenas tortor turpis, interdum non, sodales non, iaculis ac, lacus. Vestibulum auctor, tortor quis iaculis malesuada, libero lectus bibendum purus, sit amet tincidunt quam turpis vel lacus. In pellentesque nisl non sem. Suspendisse nunc sem, pretium eget, cursus a, fringilla vel, urna. Aliquam commodo ullamcorper erat. Nullam vel justo in neque porttitor laoreet. Aenean lacus dui, consequat eu, adipiscing eget, nonummy non, nisi. Morbi nunc est, dignissim non, ornare sed, luctus eu, massa. Vivamus eget quam. Vivamus tincidunt diam nec urna. Curabitur velit. Quisque dolor magna, ornare sed, elementum porta, luctus in, leo.</p>
        <p>Donec quis dui. Sed imperdiet. Nunc consequat, est eu sollicitudin gravida, mauris ligula lacinia mauris, eu porta dui nisl in velit. Nam congue, odio id auctor nonummy, augue lectus euismod nunc, in tristique turpis dolor sed urna. Donec sit amet quam eget diam fermentum pharetra. Integer tincidunt arcu ut purus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla blandit malesuada odio. Nam augue. Aenean molestie sapien in mi. Suspendisse tincidunt. Pellentesque tempus dui vitae sapien. Donec aliquam ipsum sit amet pede. Sed scelerisque mi a erat. Curabitur rutrum ullamcorper risus. Maecenas et lorem ut felis dictum viverra. Fusce sem. Donec pharetra nibh sit amet sapien.</p>
        <p>Aenean ut orci sed ligula consectetuer pretium. Aliquam odio. Nam pellentesque enim. Nam tincidunt condimentum nisi. Maecenas convallis luctus ligula. Donec accumsan ornare risus. Vestibulum id magna a nunc posuere laoreet. Integer iaculis leo vitae nibh. Nam vulputate, mauris vitae luctus pharetra, pede neque bibendum tellus, facilisis commodo diam nisi eget lacus. Duis consectetuer pulvinar nisi. Cras interdum ultricies sem. Nullam tristique. Suspendisse elementum purus eu nisl. Nulla facilisi. Phasellus ultricies ullamcorper lorem. Sed euismod ante vitae lacus. Nam nunc leo, congue vehicula, luctus ac, tempus non, ante. Morbi suscipit purus a nulla. Sed eu diam.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras imperdiet felis id velit. Ut non quam at sem dictum ullamcorper. Vestibulum pharetra purus sed pede. Aliquam ultrices, nunc in varius mattis, felis justo pretium magna, eget laoreet justo eros id eros. Aliquam elementum diam fringilla nulla. Praesent laoreet sapien vel metus. Cras tempus, sapien condimentum dictum dapibus, lorem augue fringilla orci, ut tincidunt eros nisi eget turpis. Nullam nunc nunc, eleifend et, dictum et, pharetra a, neque. Ut feugiat. Aliquam erat volutpat. Donec pretium odio nec felis. Phasellus sagittis lacus eget sapien. Donec est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        <p>Vestibulum semper. Nullam non odio. Aliquam quam. Mauris eu lectus non nunc auctor ullamcorper. Sed tincidunt molestie enim. Phasellus lobortis justo sit amet quam. Duis nulla erat, varius a, cursus in, tempor sollicitudin, mauris. Aliquam mi velit, consectetuer mattis, consequat tristique, pulvinar ac, nisl. Aliquam mattis vehicula elit. Proin quis leo sed tellus scelerisque molestie. Quisque luctus. Integer mattis. Donec id augue sed leo aliquam egestas. Quisque in sem. Donec dictum enim in dolor. Praesent non erat. Nulla ultrices vestibulum quam.</p>
        <p>Duis hendrerit, est vel lobortis sagittis, tortor erat scelerisque tortor, sed pellentesque sem enim id metus. Maecenas at pede. Nulla velit libero, dictum at, mattis quis, sagittis vel, ante. Phasellus faucibus rutrum dui. Cras mauris elit, bibendum at, feugiat non, porta id, neque. Nulla et felis nec odio mollis vehicula. Donec elementum tincidunt mauris. Duis vel dui. Fusce iaculis enim ac nulla. In risus.</p>
        <p>Donec gravida. Donec et enim. Morbi sollicitudin, lacus a facilisis pulvinar, odio turpis dapibus elit, in tincidunt turpis felis nec libero. Nam vestibulum tempus ipsum. In hac habitasse platea dictumst. Nulla facilisi. Donec semper ligula. Donec commodo tortor in quam. Etiam massa. Ut tempus ligula eget tellus. Curabitur id velit ut velit varius commodo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla facilisi. Fusce ornare pellentesque libero. Nunc rhoncus. Suspendisse potenti. Ut consequat, leo eu accumsan vehicula, justo sem lobortis elit, ac sollicitudin ipsum neque nec ante.</p>
        <p>Aliquam elementum mauris id sem. Vivamus varius, est ut nonummy consectetuer, nulla quam bibendum velit, ac gravida nisi felis sit amet urna. Aliquam nec risus. Maecenas lacinia purus ut velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sit amet dui vitae lacus fermentum sodales. Donec varius dapibus nisl. Praesent at velit id risus convallis bibendum. Aliquam felis nibh, rutrum nec, blandit non, mattis sit amet, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam varius dignissim nibh. Quisque id orci ac ante hendrerit molestie. Aliquam malesuada enim non neque.</p>
    </div>
    <div id="center1" class="x-hide-display">
        <p><b>Done reading me? Close me by clicking the X in the top right corner.</b></p>
        <p>Vestibulum semper. Nullam non odio. Aliquam quam. Mauris eu lectus non nunc auctor ullamcorper. Sed tincidunt molestie enim. Phasellus lobortis justo sit amet quam. Duis nulla erat, varius a, cursus in, tempor sollicitudin, mauris. Aliquam mi velit, consectetuer mattis, consequat tristique, pulvinar ac, nisl. Aliquam mattis vehicula elit. Proin quis leo sed tellus scelerisque molestie. Quisque luctus. Integer mattis. Donec id augue sed leo aliquam egestas. Quisque in sem. Donec dictum enim in dolor. Praesent non erat. Nulla ultrices vestibulum quam.</p>
        <p>Duis hendrerit, est vel lobortis sagittis, tortor erat scelerisque tortor, sed pellentesque sem enim id metus. Maecenas at pede. Nulla velit libero, dictum at, mattis quis, sagittis vel, ante. Phasellus faucibus rutrum dui. Cras mauris elit, bibendum at, feugiat non, porta id, neque. Nulla et felis nec odio mollis vehicula. Donec elementum tincidunt mauris. Duis vel dui. Fusce iaculis enim ac nulla. In risus.</p>
        <p>Donec gravida. Donec et enim. Morbi sollicitudin, lacus a facilisis pulvinar, odio turpis dapibus elit, in tincidunt turpis felis nec libero. Nam vestibulum tempus ipsum. In hac habitasse platea dictumst. Nulla facilisi. Donec semper ligula. Donec commodo tortor in quam. Etiam massa. Ut tempus ligula eget tellus. Curabitur id velit ut velit varius commodo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla facilisi. Fusce ornare pellentesque libero. Nunc rhoncus. Suspendisse potenti. Ut consequat, leo eu accumsan vehicula, justo sem lobortis elit, ac sollicitudin ipsum neque nec ante.</p>
        <p>Aliquam elementum mauris id sem. Vivamus varius, est ut nonummy consectetuer, nulla quam bibendum velit, ac gravida nisi felis sit amet urna. Aliquam nec risus. Maecenas lacinia purus ut velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sit amet dui vitae lacus fermentum sodales. Donec varius dapibus nisl. Praesent at velit id risus convallis bibendum. Aliquam felis nibh, rutrum nec, blandit non, mattis sit amet, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam varius dignissim nibh. Quisque id orci ac ante hendrerit molestie. Aliquam malesuada enim non neque.</p>
    </div>
    <div id="props-panel" class="x-hide-display" style="width:200px;height:200px;overflow:hidden;">
    </div>
    <div id="south" class="x-hide-display">
        operating system: <span id="platform"></span>&nbsp;&nbsp;&nbsp;&nbsp;
        browser: <span id="broswer"></span>
    </div>

app/views/boys/new.html.erb
<h1>New boy</h1>

<%= render 'form' %>

<%= link_to 'Back', boys_path %>

app/views/boys/new.js.erb
var store = Ext.create('Ext.data.TreeStore', {
    root: {
        expanded: true,
        children: [
            { text: "detention", leaf: true },
            { text: "homework", expanded: true, children: [
                { text: "book report", leaf: true },
                { text: "alegrbra", leaf: true}
            ] },
            { text: "buy lottery tickets", leaf: true }
        ]
    }
});

var my_tree = Ext.create('Ext.tree.Panel', {
    title: 'Simple Tree',
    width: 200,
    height: 150,
    store: store,
//    rootVisible: false,   
    rootVisible: true,
    autoScroll: true
});


var tree = Ext.create('Ext.tree.Panel', {
		    title: 'TreeGrid',
		    width : 200,
		    height : 120,
		    fields: ['name', 'description'],
		    columns: [{
		        xtype: 'treecolumn', 
		        text: 'name',
		        dataIndex: 'name',
		        width: 200,
		        sortable: true
		    }, {
		        text: 'describe',
		        dataIndex: 'description',
		        flex: 1,
		        sortable: true
		    }],
		    root: {
		        name: 'treeroot',
		        description: 'treerootdescribe',
		        expanded: true,
		        children: [{
		            name: 'nodeone',
		            description: 'nodedescribe',
		            leaf: true
		        }, {
		            name: 'nodetwo',
		            description: 'nodetwodescribe',
		            expanded: true,
		            children: [
				            {
				            name: 'nodeone',
				            description: 'nodedescribe',
				            leaf: true
				            }
		            ]
		        }]
		    }
		});


    Ext.regModel("OrgInfo", {
		    fields: ['parent_id','name', 'code']
		});
		var myStore = new Ext.data.TreeStore({
			model : 'OrgInfo',
			nodeParam : 'parent_id', 
			proxy: {
	            type: 'ajax',
	            url: 'code/all.json',
	            reader: 'json'
	        },
			autoLoad: true,
        root: {
            name: 'codelist',
            id: 1,
            expanded: true,
        }
		});
		
		var tree_panel = Ext.create('Ext.tree.Panel', {
		    title: 'example',
		    columns: [{
		        xtype: 'treecolumn', 
		        text: 'code array',
		        dataIndex: 'name',
		        width: 150,
		        sortable: true
		    }, {
		        text: 'code type',
		        dataIndex: 'code',
		        flex: 1,
		        sortable: true
		    }],
		    store : myStore,
		    rootVisible: true,
		    bodyStyle: {
				    background: '#ffc',
				//    padding: '10px'
				}
		});


function treeItemAdd(){
   var node_selected = tree_panel.getSelectionModel().getSelection();
   if(tree_panel.getSelectionModel().hasSelection()){
      var form = new Ext.FormPanel({
        baseCls: 'x-plain',
        labelWidth: 65,
        border:false,
        layout:"form",
        buttonAlign:"center",
        items:[
            {xtype:"textfield",anchor:'95%',fieldLabel: 'name',name: 'name',allowBlank:false}
        ],
        buttons: [
            {
                text: 'save',
                handler:function() {
                    if (form.getForm().isValid()) {
    	                Ext.Ajax.request({
                            url: 'boys/add_tree',
                            success: function(response){
                                     tree_panel.disableSelection;
                                     tree_panel.store.load();
                                     window.close()
                            },
                            failure: function(response){
                                     show_tip_message("failure")
                            },
                            params: {
                                     parent_id: node_selected[0].data.id,
                                     name:form.getForm().findField("name").getValue()
                            }
                         });
                       }
                }
            },
            {
                text: 'cancel',
                handler:function() {
                      window.close()
                }
            }
        ]
    });
    var window = new Ext.Window({
        title:"new",
        iconCls:"silk-add",
        width:280,
        height:150,
        resizable:false,
        layout:"fit",
        closeAction:'close',
        plain: true,
        constrainHeader:true,
        modal:true,
        bodyStyle: 'padding:5px;',
        items:[form]
    }).show();
 }else {
          show_tip_message("chose")
 }

};


function treeItemEdit(){
   var node_selected = tree_panel.getSelectionModel().getSelection();
   if(tree_panel.getSelectionModel().hasSelection()){
      var form = new Ext.FormPanel({
        baseCls: 'x-plain',
        labelWidth: 65,
        border:false,
        buttonAlign:"center",
        items:[
            {xtype:"textfield",anchor:'95%',fieldLabel: 'name',name: 'name',allowBlank:false}, 
        ],
        buttons: [
            {
                text: 'save',
                handler:function() {
                    if (form.getForm().isValid()) {
                       Ext.Ajax.request({
                         url: 'boys/edit_tree',
                         success: function(response){
                                   tree_panel.store.load();
                                   tree_panel.disableSelection;             
                                   window.close();
                         },
                         failure: function(response){
                              show_tip_message("false!")
                         },
                         params: {
                                    name:form.getForm().findField("name").getValue(),
                                    id: node_selected[0].data.id
                         }
                     });
                   }
                 }
             },
            {
                text: 'cancel',
                handler:function() {
                    window.close()
                }
            }
        ]
    });
    var window = new Ext.Window({
        title:"edit",
        iconCls:"silk-add",
        width:280,
        height:150,
        resizable:false,
        layout:"fit",
        closeAction:'close',
        plain: true,
        constrainHeader:true,
        modal:true,
        bodyStyle: 'padding:5px;',
        items:[form]
    });
    window.show();
    form.getForm().setValues({
         name:node_selected[0].data.name
     });
  }else{
       show_tip_message("chose one")
  }
};

function treeItemDelete(){
     var node_selected = tree_panel.getSelectionModel().getSelection();
     if(tree_panel.getSelectionModel().hasSelection()){
       if(node_selected[0].data.id==1){
         show_tip_message("notice")
       }else{
         Ext.Ajax.request({
           url: 'boys/delete_tree',
           success: function(response){
           tree_panel.store.load();
           tree_panel.disableSelection;
           
           },
           failure: function(response){
              show_tip_message("failure")
           },
           params: {
          id: node_selected[0].data.id
           }
          });}
    }else{
          show_tip_message("chose dir")
    }
};

  var code_list =new Ext.form.Panel({

        id:"note_west",

        title: 'code list',
        layout: 'fit',
        bbar:  
        [
            { xtype: 'button', text: 'add', iconCls:"silk-user_add",handler: function(){ treeItemAdd()} },
            { xtype: 'button', text: 'edit', iconCls:"silk-user_edit", handler: function() {
                    treeItemEdit();
            }},
            { xtype: 'button', text: 'delete', iconCls:"silk-user_delete", handler: function() {
                treeItemDelete();
            }},

         ],

        autoScroll: true,

        items: tree_panel

    });


	var datas = [
			[100,'three',24],
			[200,'four',30],
			[300,'five',29]
		];
	
	var my_grid =	Ext.create('Ext.grid.Panel',{
			title : 'Grid example',
			frame:true,
			viewConfig: {
				forceFit : true,
	            stripeRows: true
	        },
			store: {
		        fields: ['id','name','age'],
		        proxy: {
		            type: 'memory',
		            data : datas,
		            reader : 'array'
		        },
		        autoLoad: true
		    },
			columns: [
				{header: "id", width: 30, dataIndex: 'id', sortable: true},
				{header: "name", width: 80, dataIndex: 'name', sortable: true},
				{header: "age", width: 80, dataIndex: 'age', sortable: true}
			],
			tbar: [
         { xtype: 'button', text: 'Button 1' },
         {text: 'new'}, {text: 'open'},
	    {text: 'edit'}, {text: 'save'},
	    '-', 
	    {
	    	xtype: 'textfield',
	    	hideLabel: true,
	    	width: 150
	    },
	    '->', 
	    '<a href=#>hyperlink</a>',
	    {
	    	xtype: 'tbspacer', 
	    	width: 50
	    },
	    'static text'
      ]
		});

 var upload = Ext.create('Ext.form.Panel', {
        width: 500,
        frame: true,
        title: 'File Upload Form',
        bodyPadding: '10 10 0',
        height: 300,
        defaults: {
            anchor: '100%',
            allowBlank: false,
            msgTarget: 'side',
            labelWidth: 50
        },

        items: [
//        {
//            xtype: 'textfield',
//            fieldLabel: 'Name'
//        },
          {
            xtype: 'filefield',
            id: 'form-file',
            emptyText: 'Select an image',
            fieldLabel: 'Photo',
            name: 'photo',
            buttonText: '',
            buttonConfig: {
                iconCls: 'upload-icon'
            }
        }],

        buttons: [{
            text: 'Save',
            handler: function(){
               var form = this.up('form').getForm();
                if(form.isValid()){
                    form.submit({
                        url: 'upload/upload.json',
                        waitMsg: 'Uploading your photo...',
                        success: function(fp, o) {
                           show_tip_message("false"),
													 form.reset()
                        }
                    });
                }
             
            }
        },{
            text: 'Reset',
            handler: function() {
                this.up('form').getForm().reset();
            }
        }]
    });


var car_tabPanel = new Ext.TabPanel({

		id:"car_tabPanels",
	
		activeTab: 4,

    resizeTabs:true,

    border:false,

    tabWidth:170,

    minTabWidth: 150,

    autoDestroy:true,

    enableTabScroll:true,

    defaults:{

        layout:"fit"

    },

   items: [
				{title: 'tab1',html : 'tab1content'},
				{title: 'tab2',html : 'tab2content'},
				upload,
				my_grid,
				my_tree,
				tree,
				code_list
			]

});

var work_space = Ext.getCmp('work-space');

work_space.removeAll();

work_space.add(car_tabPanel);

work_space.doLayout();

app/views/boys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @boy.name %>
</p>


<%= link_to 'Edit', edit_boy_path(@boy) %> |
<%= link_to 'Back', boys_path %>