config/routes.rb
Codeapp::Application.routes.draw do
	match "girls/girl_add"=>"girls#girl_add"
	match "girls/girl_edit"=>"girls#girl_edit"
	match "girls/girl_delete"=>"girls#girl_delete"
	match "girls/girl_search"=>"girls#girl_search"
	match "upload/uploadin"=>"upload#uploadin"
	match "upload/uploadout"=>"upload#uploadout"
	match "upload/upload"=>"upload#upload"
	match "boys/add_tree"=>"boys#add_tree"
	match "boys/delete_tree"=>"boys#delete_tree"
	match "boys/edit_tree"=>"boys#edit_tree"
	match "boys/all_delete"=>"boys#all_delete"
	match "code/ajax"=>"code#ajax"
	match "code/list"=>"code#list"
	match "manager/all"=>"manager#all"
  resources :girls
 
  post "girls/try"=>'girls#try'
  get "users/new"
  
  resources :boys

   match ':controller(/:action(/:id))(.:format)'
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
  # GET /girls
  # GET /girls.json
  layout false
  def index
    if params[:search_type]!='0'
    if params[:search_type] == '101100'
    @girls = Girl.find(:all, :conditions => ["name like ?","%#{params[:value]}%"])
    totalCount=Girl.find(:all, :conditions => ["name like ?","%#{params[:value]}%"]).count
    elsif params[:search_type] == '100000'
    @girls = Girl.find(:all,  :conditions => ["email like ?","%#{params[:value]}%"])
    totalCount=Girl.find(:all, :conditions =>["email like ?","%#{params[:value]}%"]).count
    else
    @girls = Girl.find(:all,  :conditions => ["phone like ?","%#{params[:value]}%"])
    totalCount=Girl.find(:all, :conditions =>["phone like ?","%#{params[:value]}%"]).count
    end
    else
    @girls = Girl.find(:all, :offset=>params[:start].to_i, :limit=>params[:limit].to_i)
    if !Girl.count.nil? & @girls.empty?
    @girls=Girl.find(:all, :offset=>(params[:start].to_i-params[:limit].to_i), :limit=>params[:limit].to_i)
    end
    totalCount=Girl.count
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: { :totalCount=>totalCount, :gridData=> @girls } }
      format.js
    end
  end

  def try
  @girls = Girl.find(:all, :offset=>params[:start].to_i, :limit=>params[:limit].to_i)
  respond_to do |format|
  	 format.json { render json: { :totalCount=>Girl.count, :gridData=> @girls } }
  	end
  end
  
  def girl_search
  if(params[:search_type]=='101100')
  @girls=Girl.find(:all, :offset=>params[:start].to_i, :limit=>params[:limit], :conditions=>["name like ?","%#{params[:value]}%"])
	end
	respond_to do |format|
  	 format.json { render json: { :totalCount=>Girl.find(:all, :offset=>params[:start].to_i, :limit=>params[:limit], :conditions=>["name = ?","%#{params[:value]}%"]).count, :gridData=> @girls } }
  	end
	end
  
  def girl_add
  Girl.create(:name=>params[:name], :email=>params[:email], :phone=>params[:phone])
  respond_to do |format|
  	format.json { render :json=>{:success=>true} }
  end
  end

  def girl_edit
  @girl = Girl.find(params[:id])
  @girl.update_attributes(:name=>params[:name], :email=>params[:email], :phone=>params[:phone])
   respond_to do |format|
  	format.json { render :json=>{:success=>true}}
  end
  end
  
  def girl_delete
  @girl = Girl.find(params[:id])
  @girl.destroy
   respond_to do |format|
  	format.json { render :json=>{:success=>true}}
  end
  end

  # GET /girls/1
  # GET /girls/1.json
  def show
    @girl = Girl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @girl }
    end
  end

  # GET /girls/new
  # GET /girls/new.json
  def new
    @girl = Girl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @girl }
    end
  end

  # GET /girls/1/edit
  def edit
    @girl = Girl.find(params[:id])
  end

  # POST /girls
  # POST /girls.json
  def create
    @girl = Girl.new(params[:girl])

    respond_to do |format|
      if @girl.save
        format.html { redirect_to @girl, notice: 'Girl was successfully created.' }
        format.json { render json: @girl, status: :created, location: @girl }
      else
        format.html { render action: "new" }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /girls/1
  # PUT /girls/1.json
  def update
    @girl = Girl.find(params[:id])

    respond_to do |format|
      if @girl.update_attributes(params[:girl])
        format.html { redirect_to @girl, notice: 'Girl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @girl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /girls/1
  # DELETE /girls/1.json
  def destroy
    @girl = Girl.find(params[:id])
    @girl.destroy

    respond_to do |format|
      format.html { redirect_to girls_url }
      format.json { head :no_content }
    end
  end
end

app/views/girls/_form.html.erb
<%= form_for(@girl) do |f| %>
  <% if @girl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@girl.errors.count, "error") %> prohibited this girl from being saved:</h2>

      <ul>
      <% @girl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/girls/edit.html.erb
<h1>Editing girl</h1>

<%= render 'form' %>

<%= link_to 'Show', @girl %> |
<%= link_to 'Back', girls_path %>

app/views/girls/index.html.erb
<h1>Listing girls</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @girls.each do |girl| %>
  <tr>
    <td><%= girl.name %></td>
    <td><%= girl.email %></td>
    <td><%= girl.phone %></td>
    <td><%= link_to 'Show', girl %></td>
    <td><%= link_to 'Edit', edit_girl_path(girl) %></td>
    <td><%= link_to 'Destroy', girl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @girls %>
<br />

<%= link_to 'New Girl', new_girl_path %>

app/views/girls/index.js.erb

function user_action_handler(type) {

    var form = new Ext.form.Panel({

        baseCls: 'x-plain',

        labelWidth: 60,

        border:false,

        layout:"form",

        items: [
            {xtype:"hidden",name: "id"},
            {xtype:"textfield",fieldLabel: 'name', name: "name",emptyText:"enter user",allowBlank:false,anchor:'95%'},

            {xtype:"textfield",fieldLabel: 'E-mail',vtype:"email",name: "email",anchor:'95%'},

            {xtype:"numberfield",fieldLabel: 'phone',allowNegative:false,allowDecimals:false,name: "phone",anchor:'95%'}           

        ],

        buttonAlign:"center",
        
        buttons: [

            {
                text: 'save',

                handler:function() {
                   
                    if (form.getForm().isValid()) {
                      switch (type) {
                      case "add":
                     
                     Ext.Ajax.request({
									    url: 'girls/girl_add',
									    params: form.getForm().getValues(),
									    success: function(response){
									       var obj = Ext.decode(response.responseText);
	                        if (obj.success) {
	                             edit_window.close();
	                             store.reload();
	                        } else {
	                            show_tip_message("false")
	                        }
                          },
                      failure: function(response) {
                              show_tip_message("false")
                          }                
                      });
                      break;
                      case "edit": 
                       Ext.Ajax.request({
									    url: 'girls/girl_edit',
									    params: form.getForm().getValues(),
									    success: function(response){
									       var obj = Ext.decode(response.responseText);
	                        if (obj.success) {
	                             edit_window.close();
	                             store.reload();
	                        } else {
	                            show_tip_message("false")
	                        }
                          },
                      failure: function(response) {
                              show_tip_message("false")
                          }                
                      });
                      break;
                      
                    
                      
                      }     //switch
                
                   }       //form
                    
                   }      //handler 
                   

             },                    

            {

                text: 'cancel',

                handler:function() {

                    edit_window.close()

                }

            }

        ]

        });

    var edit_window = new Ext.Window({

        width:380,

        height:270,

        resizable:false,

        layout:"fit",

        closeAction:'close',

        plain: true,

        constrainHeader:true,

        modal:true,

        bodyStyle: 'padding:5px;',

        items:[form]

    });

  var rows = grid_json.getSelectionModel().getSelection();

    if (type == "add") {

      //  user_role_store.load();

        edit_window.show();

        edit_window.setTitle("add user");

    //    edit_window.setIconClass("silk-user_add");

    }  else if(type == "edit"){
           if(rows.length==1){
            form.getForm().setValues({
                id:rows[0].get("id"),
                name:rows[0].get("name"),

                email:rows[0].get("email"),

                phone:rows[0].get("phone"),

            });
            edit_window.show();
            }
            else
            {
            show_tip_message("chose a data")
             }
          

        }
        else
        {
                     if(rows.length==1){
                       Ext.Ajax.request({
									    url: 'girls/girl_delete',
									    params: { id : rows[0].get("id") },
									    success: function(response){
									       var obj = Ext.decode(response.responseText);
	                        if (obj.success) {
	                             store.reload();
	                        } else {
	                            show_tip_message("false")
	                        }
                          },
                      failure: function(response) {
                              show_tip_message("false")
                          }                
                      });
                      }
                      else
                      {
                       show_tip_message("chose a data")
                      }
                   
        
        }
}




 itemsPerPage = 2;   // set the number of items you want per page


var store = Ext.create('Ext.data.Store', {
    id:'simpsonsStore',
    autoLoad: false,
    fields:['name', 'email', 'phone'],
    pageSize: itemsPerPage, // items per page
    proxy: {
        type: 'ajax',
        url: 'girls.json',  // url that will load data with respect to start and limit params
        reader: {
            type: 'json',
            root: 'gridData',
            totalProperty: 'totalCount'
        },
    extraParams : {
        value : <%= params[:value].nil? ? 0 : params[:value] %>,
        search_type: <%= params[:search_type].nil? ? 0 : params[:search_type] %>
     }
    }  
});

// specify segment of data you want to load using params
store.load({
    params:{
        start:0,
        limit: itemsPerPage,

    }
});
////////////
Ext.regModel('PostInfo', {
		    fields: [{name: 'province'},{name: 'post'}]
		});
		
var postStore = Ext.create('Ext.data.Store',{
			model : 'PostInfo',
			data : [
				{province:'email',post:'100000'},
				{province:'name',post:'101100'},
				{province:'phone',post:'102200'}
			]
		});		

function vehicle_search(type){

    if(type=="search"){

        if(Ext.getCmp("search_vehicle").isValid()){

            Ext.getCmp("clear_vehicle_button").enable();
            store.load({
					    params:{
					        start:0,
					        limit: 2,
					        value : Ext.getCmp("search_vehicle").getValue(),
                  search_type: Ext.getCmp("search_in_vehicle_list_id").getValue()
					    }
              });
          

        }else{

            show_tip_message("enter something")

        }

    }else if(type=="clear"){

        Ext.getCmp("clear_vehicle_button").disable();
        Ext.getCmp("search_vehicle").setValue('');
        store.load({
					    params:{
					        start:0,
					        limit: 2,
					    }
              });

    }

}

///////////

var grid_json=Ext.create('Ext.grid.Panel', {
    title: 'Simpsons',
    store: store,
    columns: [
        { header: 'Name',  dataIndex: 'name' },
        { header: 'Email', dataIndex: 'email', flex: 1 },
        { header: 'Phone', dataIndex: 'phone' }
    ],
    width: 400,
    height: 125,
    selType: 'rowmodel',
    dockedItems: [{
        xtype: 'pagingtoolbar',
        store: store,   // same store GridPanel is using
        dock: 'bottom',
        displayInfo: true,   
        items:[
                '-',
                { text: '<%= t(:add) %>', iconCls:"silk-user_add", handler: function() {
                    user_action_handler("add")
                }},
                { text: '<%= t(:edit) %>', iconCls:"silk-user_edit", handler: function() {
                    user_action_handler("edit");
          //          var rows = grid.getSelectionModel().getSelection();
                }},
                { text: '<%= t(:delete) %>', iconCls:"silk-user_delete", handler: function() {
                    user_action_handler("delete")
                }},
                {
						    	xtype: 'textfield',
						    	hideLabel: true,
						    	width: 150,
						    	id: "search_vehicle",
						    	allowBlank:false,
						    },
                {
                  id:"search_in_vehicle_list_id",
									xtype : 'combo',
									listConfig : {
										emptyText : 'no match data', 
										maxHeight : 60 
									},
  								name:'post',
									autoSelect : true,
//								fieldLabel:'post',
									triggerAction: 'all', 
									store : postStore, 
									displayField:'province', 
									valueField:'post', 
									queryMode: 'local', 
									forceSelection : true, 
									typeAhead : true, 
									value:'101100',
//								multiSelect: true
								},
								{ text: 'search',id:"search_vehicle_button", iconCls:"silk-zoom", handler:function(){vehicle_search("search")} },
                { text: 'clear', id:"clear_vehicle_button", disabled:true, handler: function(){vehicle_search("clear")} }
                ]       
    }],
});



var work_space = Ext.getCmp('work-space');

work_space.removeAll();

work_space.add(grid_json);

work_space.doLayout();

app/views/girls/new.html.erb
<h1>New girl</h1>

<%= render 'form' %>

<%= link_to 'Back', girls_path %>

app/views/girls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @girl.name %>
</p>

<p>
  <b>Email:</b>
  <%= @girl.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @girl.phone %>
</p>


<%= link_to 'Edit', edit_girl_path(@girl) %> |
<%= link_to 'Back', girls_path %>

app/views/girls/try.js.erb
var itemsPerPage = 2;   // set the number of items you want per page

var store = Ext.create('Ext.data.Store', {
    id:'simpsonsStore',
    autoLoad: false,
    fields:['name', 'email', 'phone'],
    pageSize: itemsPerPage, // items per page
    proxy: {
        type: 'ajax',
        url: 'girls.json',  // url that will load data with respect to start and limit params
        reader: {
            type: 'json',
            root: 'localhost:3000',
        }
    }  
});

// specify segment of data you want to load using params
store.load({
    params:{
        start:0,
        limit: itemsPerPage,

    }
});

var grid_json=Ext.create('Ext.grid.Panel', {
    title: 'Simpsons',
    store: store,
    columns: [
        { header: 'Name',  dataIndex: 'name' },
        { header: 'Email', dataIndex: 'email', flex: 1 },
        { header: 'Phone', dataIndex: 'phone' }
    ],
    width: 400,
    height: 125,
    dockedItems: [{
        xtype: 'pagingtoolbar',
        store: store,   // same store GridPanel is using
        dock: 'bottom',
        displayInfo: true
    }],
});

var work_space = Ext.getCmp('work-space');

work_space.removeAll();

work_space.add(grid_json);

work_space.doLayout();