config/routes.rb
Codeapp::Application.routes.draw do
	match "girls/girl_add"=>"girls#girl_add"
	match "girls/girl_edit"=>"girls#girl_edit"
	match "girls/girl_delete"=>"girls#girl_delete"
	match "girls/girl_search"=>"girls#girl_search"
	match "upload/uploadin"=>"upload#uploadin"
	match "upload/uploadout"=>"upload#uploadout"
	match "upload/upload"=>"upload#upload"
	match "boys/add_tree"=>"boys#add_tree"
	match "boys/delete_tree"=>"boys#delete_tree"
	match "boys/edit_tree"=>"boys#edit_tree"
	match "boys/all_delete"=>"boys#all_delete"
	match "code/ajax"=>"code#ajax"
	match "code/list"=>"code#list"
	match "manager/all"=>"manager#all"
  resources :girls
 
  post "girls/try"=>'girls#try'
  get "users/new"
  
  resources :boys

   match ':controller(/:action(/:id))(.:format)'
end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :code, :codeLength, :comment, :describe, :footprint, :manufacturer, :name, :parent_id, :partNum, :quantity, :unitprice
end

app/controllers/code_controller.rb
class CodeController < ApplicationController
layout "special"

def code_add
@codeA=Code.find(params[:parent_id].to_i)
@codeB=Code.find(@codeA.parent_id)
@code=@codeB.code+@codeA.code+params[:code]
flag = true
@codes=Code.where(:parent_id=>params[:parent_id])
@codes.each do |code|
if code.code==@code
flag=false
end
end
if flag
Code.create(:name=>params[:name], :parent_id=>params[:parent_id], :code=>@code, :footprint=>params[:footprint], :manufacturer=>params[:manufacturer], :partNum=>params[:partNum], :describe=>params[:describe])
end
respond_to do |format|
	format.json { render :json=>{:success=>flag} }
end
end

def code_edit
@codeA=Code.find(params[:parent_id].to_i)
@codeB=Code.find(@codeA.parent_id)
@codeC=@codeB.code+@codeA.code+params[:code]
flag = true
@codes=Code.where(:parent_id=>params[:parent_id])
@codes.each do |code|
if code.code==@codeC  && code.id != params[:id].to_i
flag=false
end
end
if flag
@code = Code.find(params[:id])
@code.update_attributes(:name=>params[:name], :code=>@codeC, :footprint=>params[:footprint], :manufacturer=>params[:manufacturer], :partNum=>params[:partNum], :describe=>params[:describe])
end
 respond_to do |format|
	format.json { render :json=>{:success=>flag}}
end
end

def code_delete
ids = params[:id].split(/,/)
ids.each do |id|
@code = Code.find(id)
@code.destroy
end
 respond_to do |format|
	format.json { render :json=>{:success=>true}}
end
end
  
def node_add
flag = true
@codes=Code.where(:parent_id=>params[:id])
@codes.each do |code|
if code.code==params[:code]
flag=false
end
end
if flag
Code.create(:codeLength=>false, :name=>params[:name], :parent_id=>params[:id], :code=>params[:code]) 
end
respond_to do |format|
	format.json { render :json=>{:success=>flag} }
end
end 

def node_edit
flag = true
@codes=Code.where(:parent_id=>params[:parent_id])
@codes.each do |code|
if code.code==params[:code] && code.id != params[:id].to_i
flag=false
end
end
if flag
@code = Code.find(params[:id])
@code.update_attributes(:name=>params[:name], :code=>params[:code]) 
end
respond_to do |format|
	format.json { render :json=>{:success=>flag} }
end
end 

def node_delete
@code = Code.find(params[:id])
@code.destroy 
respond_to do |format|
	format.json { render :json=>{:success=>true} }
end
end

def get
respond_to do |format|
	format.js
end
end
   
def all
@codes=Code.order("code ASC").where(:parent_id=>params[:parent_id])
respond_to do |format|
	format.json { render json: @codes }
end
end

def lists
if params[:search_type]!='0'
if params[:search_type] == '101100'

if params[:value1].empty? && params[:value2].empty?
@codes = Code.order("code ASC").find(:all, :offset=>params[:start].to_i, :limit=>params[:limit].to_i, :conditions=>{:parent_id=>params[:parent_id]})
if !Code.count.nil? & @codes.empty?
@codes=Code.find(:all, :offset=>(params[:start].to_i-params[:limit].to_i), :limit=>params[:limit].to_i, :conditions=>{:parent_id=>params[:parent_id]})
end
totalCount=2
elsif params[:value1].empty? && !params[:value2].empty?
@codes = Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%") 
#totalCount=Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%").count
totalCount=2
elsif !params[:value1].empty? && params[:value2].empty?
@codes = Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%") 
#totalCount=Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%").count
totalCount=2
else !params[:value1].empty? && !params[:value2].empty?
@codes = Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%").where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%")
#totalCount=Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%").where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%").count
totalCount=2
end

elsif params[:search_type] == '100000'


@codes = Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ? or name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%")
totalCount=Code.where(:parent_id=>params[:parent_id]).where("name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ? or name like ? or code like ? or partNum like ? or footprint like ? or manufacturer like ? or describe like ?","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value1]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%","%#{params[:value2]}%").count


end
else
@codes = Code.order("code ASC").find(:all, :offset=>params[:start].to_i, :limit=>params[:limit].to_i, :conditions=>{:parent_id=>params[:parent_id]})
if !Code.count.nil? & @codes.empty?
@codes=Code.find(:all, :offset=>(params[:start].to_i-params[:limit].to_i), :limit=>params[:limit].to_i, :conditions=>{:parent_id=>params[:parent_id]})
end
totalCount=Code.find(:all, :conditions=>{:parent_id=>params[:parent_id]}).count
end

respond_to do |format|
	format.html # index.html.erb
	format.json { render json: { :totalCount=>totalCount, :gridData=> @codes } }
	format.js 
end
end

def list
respond_to do |format|
	format.js 
end
end

def ajax
respond_to do |format|
	format.html
	format.js
end
end

end

app/views/code/ajax.html.erb
hello world<%= link_to "ajax", code_ajax_path(:format=>:js), :remote=>true %>


app/views/code/ajax.js.erb
var e1=Ext.get('ajax');
e1.addCls("special-css");
  Ext.create('Ext.data.Store', {
    storeId:'simpsonsStore',
    fields:['name', 'email', 'phone'],
    data:{'items':[
        { 'name': 'Lisa',  "email":"lisa@simpsons.com",  "phone":"555-111-1224"  },
        { 'name': 'Bart',  "email":"bart@simpsons.com",  "phone":"555-222-1234" },
        { 'name': 'Homer', "email":"home@simpsons.com",  "phone":"555-222-1244"  },
        { 'name': 'Marge', "email":"marge@simpsons.com", "phone":"555-222-1254"  }
    ]},
    proxy: {
        type: 'memory',
        reader: {
            type: 'json',
            root: 'items'
        }
    }
});

Ext.create('Ext.grid.Panel', {
    title: 'Simpsons',
    store: Ext.data.StoreManager.lookup('simpsonsStore'),
    columns: [
        { text: 'Name',  dataIndex: 'name' },
        { text: 'Email', dataIndex: 'email', flex: 1 },
        { text: 'Phone', dataIndex: 'phone' }
    ],
    height: 200,
    width: 400,
    renderTo: Ext.getBody()
});

app/views/code/get.js.erb
 var form = new Ext.form.Panel({
      baseCls: 'x-plain',
      labelWidth: 60,
      border:false,
      layout:"form",
      items: [
          {xtype:"hidden",name: "id", value: record.get('id')},
          {xtype:"hidden",name: "parent_id", value: record.get('parent_id')},
          {xtype:"textfield",fieldLabel: 'name', name: "name",emptyText:"enter user",allowBlank:false,anchor:'95%'},
          {xtype:"textfield",fieldLabel: 'code',name: "code",anchor:'95%', regex : /^(\d{2})$/,
					   regexText:'only can enter two number'}       
      ],
      buttonAlign:"center",     
      buttons: [
          {
              text: 'save',
              handler:function() {     
                  if (form.getForm().isValid()) {
                  	switch (type) {
                    case "add":
                    
                   Ext.Ajax.request({
								    url: 'code/node_add',
								    params: form.getForm().getValues(),
								    success: function(response){
								       var obj = Ext.decode(response.responseText);
                        if (obj.success) {
                             edit_window.close();
                             myStore.load();
                        } else {
                            show_tip_message("you enter the same code")
                        }
                        },
                    failure: function(response) {
                            show_tip_message("network false")
                        }                
                    });
                    break;   
                    case "edit":
                   
                      Ext.Ajax.request({
									    url: 'code/node_edit',
									    params: form.getForm().getValues(),
									    success: function(response){
									       var obj = Ext.decode(response.responseText);
	                        if (obj.success) {
	                             edit_window.close();
	                             myStore.load();
	                        } else {
	                            show_tip_message("code repeat")
	                        }
                          },
                      failure: function(response) {
                              show_tip_message("false")
                          }                
                      });
                    break;
                  }       //switch
                 }       //form
                 }      //handler 
           },                    
          {
              text: 'cancel',
              handler:function() {
                  edit_window.close()
              }
          }
      ]
      });
  var edit_window = new Ext.Window({
      width:380,
      height:270,
      resizable:false,
      layout:"fit",
      closeAction:'close',
      plain: true,
      constrainHeader:true,
      modal:true,
      bodyStyle: 'padding:5px;',
      items:[form]
  });
  
   if (type == "add") {
    if (record.get('parent_id')!=1 && record.get('parent_id')!='')
    alert("you can't add");
    else {
    edit_window.show();
    edit_window.setTitle("add node");
    }
    } else if(type == "edit"){
    form.getForm().setValues({
            name:record.get('name'),
            code:record.get('code')
        });
        edit_window.show();
    edit_window.setTitle("edit node");
        }
    else { 
      Ext.MessageBox.confirm('Delete', 'Are you sure ?', function(btn){
							   if(btn === 'yes'){
							  Ext.Ajax.request({
							    url: 'code/node_delete',
							    params: { id : record.get('id') },
							    success: function(response){
							       var obj = Ext.decode(response.responseText);
                      if (obj.success) {
                           myStore.load();
                      } else {
                          show_tip_message("false")
                      }
                      },
                  failure: function(response) {
                          show_tip_message("false")
                      }                
                 });
							   }
							   else{
							      alert('cancel')
							   }
							 });
    
    }
   
  

app/views/code/list.js.erb
function code_action_handler(type) {

    var form = new Ext.form.Panel({

        baseCls: 'x-plain',

        labelWidth: 60,

        border:false,

        layout:"form",

        items: [
            {xtype:"hidden",name: "id"},
            {xtype:"hidden",name: "parent_id", value: <%= params[:id].to_i %> },
            {xtype:"textfield",fieldLabel: 'code',name: "code",allowBlank:false, anchor:'95%', regex : /^(\d{4})$/,
					   regexText:'only can enter four number'}, 
            {xtype:"textfield",fieldLabel: 'partName', name: "name",emptyText:"enter user",anchor:'95%'},
            {xtype:"textfield",fieldLabel: 'partNum', name: "partNum",anchor:'95%'},
            {xtype:"textfield",fieldLabel: 'footprint',name: "footprint",allowBlank:false,anchor:'95%'},
            {xtype:"textfield",fieldLabel: 'manufacturer', name: "manufacturer",anchor:'95%'},
            {xtype:"textarea",fieldLabel: 'describe',name: "describe",anchor:'95%'}                 

        ],

        buttonAlign:"center",
        
        buttons: [

            {
                text: 'save',

                handler:function() {
                   
                    if (form.getForm().isValid()) {
                      switch (type) {
                      case "add":
                     
                     Ext.Ajax.request({
									    url: 'code/code_add',
									    params: form.getForm().getValues(),
									    success: function(response){
									       var obj = Ext.decode(response.responseText);
	                        if (obj.success) {
	                             edit_window.close();
	                             m_store.reload();
	                        } else {
	                            show_tip_message("code repeat")
	                        }
                          },
                      failure: function(response) {
                              show_tip_message("network false")
                          }                
                      });
                      break;
                      case "edit": 
                       Ext.Ajax.request({
									    url: 'code/code_edit',
									    params: form.getForm().getValues(),
									    success: function(response){
									       var obj = Ext.decode(response.responseText);
	                        if (obj.success) {
	                             edit_window.close();
	                             m_store.reload();
	                        } else {
	                            show_tip_message("code repeat")
	                        }
                          },
                      failure: function(response) {
                              show_tip_message("false")
                          }                
                      });
                      break;
                      
                    
                      
                      }     //switch
                
                   }       //form
                    
                   }      //handler 
                   

             },                    

            {

                text: 'cancel',

                handler:function() {

                    edit_window.close()

                }

            }

        ]

        });

    var edit_window = new Ext.Window({

        width:380,

        height:350,

        resizable:false,

        layout:"fit",

        closeAction:'close',

        plain: true,

        constrainHeader:true,

        modal:true,

        bodyStyle: 'padding:5px;',

        items:[form]

    });

  var rows = m_codegrid.getSelectionModel().getSelection();

    if (type == "add") {

      //  user_role_store.load();

        edit_window.show();

        edit_window.setTitle("add user");

    //    edit_window.setIconClass("silk-user_add");

    }  else if(type == "edit"){
           if(rows.length==1){
            form.getForm().setValues({
                id:rows[0].get("id"),
                name:rows[0].get("name"),
                footprint: rows[0].get("footprint"),
                manufacturer: rows[0].get("manufacturer"),
                partNum: rows[0].get("partNum"),
                describe: rows[0].get("describe"),
                code: rows[0].get("code").substr(4,7)

            });
            edit_window.show();
            }
           else if(rows.length>1)
           {
            show_tip_message("you  chose one more data")
           }
           else {
            show_tip_message(" chose a data")
           }

        }
        else
        {
             if(rows.length!=0){
             var delete_id="";
             for(var i=0; i<rows.length; i++){
               delete_id+=rows[i].get("id");
               if(i!=rows.length-1){
                    delete_id+=",";
                }
              };
              Ext.MessageBox.confirm('Delete', 'Are you sure ?', function(btn){
							   if(btn === 'yes'){
							  Ext.Ajax.request({
							    url: 'code/code_delete',
							    params: { id : delete_id },
							    success: function(response){
							       var obj = Ext.decode(response.responseText);
                      if (obj.success) {
                           m_store.reload();
                      } else {
                          show_tip_message("false")
                      }
                      },
                  failure: function(response) {
                          show_tip_message("false")
                      }                
                 });
							   }
							   else{
							      alert('cancel')
							   }
							 });
              }
              else
              {
               show_tip_message("chose a data")
              }
                   
        
        }
}

function code_search(type){

    if(type=="search"){

        if(Ext.getCmp("search_code").isValid()){

            Ext.getCmp("clear_code_button").enable();
            m_store.load({
					    params:{
		       //      start:0,
				   //      limit: 20,		
					        value1 : Ext.getCmp("search_code1").getValue(),
					        value2 : Ext.getCmp("search_code2").getValue(),
                  search_type: Ext.getCmp("search_code").getValue()
					    }
              });
          

        }else{

            show_tip_message("enter something")

        }

    }else if(type=="clear"){

        Ext.getCmp("clear_code_button").disable();
        Ext.getCmp("search_code1").setValue('');
        Ext.getCmp("search_code2").setValue('');
        m_store.load({
					    params:{
					        start:0,
					        limit: 2,
					        parent_id : <%= params[:id].to_i %>
					    }
              });

    }

}


Ext.regModel('PostInfo', {
		    fields: [{name: 'key'},{name: 'value'}]
		});
		
var postStore = Ext.create('Ext.data.Store',{
			model : 'PostInfo',
			data : [
				{key:'or',value:'100000'},
				{key:'and',value:'101100'}
			]
		});	

        var m_itemsPerPage = 2;   // set the number of items you want per page
    
				var m_store = Ext.create('Ext.data.Store', {
				    id:'simpsonsStore',
				    autoLoad: false,
				    fields:['describe','name', 'code', 'partNum', 'footprint', 'manufacturer'],
				    pageSize: m_itemsPerPage, // items per page
				    proxy: {
				        type: 'ajax',
				        url: 'code/lists.json',  // url that will load data with respect to start and limit params
				         extraParams : {
                  parent_id : <%= params[:id].to_i %>,
                  value1 : <%= params[:value1].nil? ? 0 : params[:value1] %>,
			            value2 : <%= params[:value2].nil? ? 0 : params[:value2] %>,
			            search_type: <%= params[:search_type].nil? ? 0 : params[:search_type] %>
                },
				        reader: {
				            type: 'json',
				            root: 'gridData',
				            totalProperty: 'totalCount'
				        }
				    }  
				});
				
				// specify segment of data you want to load using params
				m_store.load({
				    params:{
				        start:0,
				        limit: m_itemsPerPage,
				        parent_id: <%= params[:id].to_i %>
				    }
				});
				
				var m_codegrid=Ext.create('Ext.grid.Panel', {
				    title: 'Simpsons',
				    store: m_store,
				    columns: [
				        { header: '<%= t('code') %>', dataIndex: 'code', flex: 1 },
				        { header: '<%= t('name') %>',  dataIndex: 'name', flex: 1 },
				        { header: '<%= t('partNum') %>', dataIndex: 'partNum', flex: 1 },
				        { header: '<%= t('footprint') %>', dataIndex: 'footprint', flex: 1 },
				        { header: '<%= t('manufacturer') %>',  dataIndex: 'manufacturer', flex: 1 },
				        { header: '<%= t('describe') %>', dataIndex: 'describe', flex: 1 }     
				    ],
				    width: 400,
				    height: 125,
				    multiSelect : true,
				    selType: 'rowmodel',
				    dockedItems: [{
				        xtype: 'pagingtoolbar',
				        store: m_store,   // same store GridPanel is using
				        dock: 'bottom',
				        displayInfo: true,   
				        items:[
				                '-',
				                { text: '<%= t('add') %>', iconCls:"silk-user_add", handler: function() {
				                    code_action_handler("add")
				                }},
				                { text: '<%= t('edit') %>', iconCls:"silk-user_edit", handler: function() {
				                   code_action_handler("edit")
				                }},
				                { text: '<%= t('delete') %>', iconCls:"silk-user_delete", handler: function() {
				                   code_action_handler("delete")
				                }},
				                {
										    	xtype: 'textfield',
										    	hideLabel: true,
										    	width: 150,
										    	id: "search_code1",
										 //   	allowBlank:false,
										    },
				                {
				                  id:"search_code",
													xtype : 'combo',
													listConfig : {
														emptyText : 'no match data', 
														maxHeight : 60 
													},
				  								name:'post',
													autoSelect : true,
													triggerAction: 'all', 
													store : postStore, 
													displayField:'key', 
													valueField:'value', 
													queryMode: 'local', 
													forceSelection : true, 
													typeAhead : true, 
													value:'101100',
							//						editable: false
												},
												{
										    	xtype: 'textfield',
										    	hideLabel: true,
										    	width: 150,
										    	id: "search_code2",
										    	allowBlank:true,
										    },
												{ text: '<%= t('search') %>',id:"search_code_button", iconCls:"silk-zoom", handler:function(){code_search("search")} },
				                { text: '<%= t('clear') %>', id:"clear_code_button", disabled:true, handler: function(){code_search("clear")} }
				                ]       
				    }],
				});

				var m_work_space = Ext.getCmp('work-space');

				m_work_space.removeAll();
				
				m_work_space.add(m_codegrid);
				
				m_work_space.doLayout();
			