config/routes.rb
Codeapp::Application.routes.draw do
	match "girls/girl_add"=>"girls#girl_add"
	match "girls/girl_edit"=>"girls#girl_edit"
	match "girls/girl_delete"=>"girls#girl_delete"
	match "girls/girl_search"=>"girls#girl_search"
	match "upload/uploadin"=>"upload#uploadin"
	match "upload/uploadout"=>"upload#uploadout"
	match "upload/upload"=>"upload#upload"
	match "boys/add_tree"=>"boys#add_tree"
	match "boys/delete_tree"=>"boys#delete_tree"
	match "boys/edit_tree"=>"boys#edit_tree"
	match "boys/all_delete"=>"boys#all_delete"
	match "code/ajax"=>"code#ajax"
	match "code/list"=>"code#list"
	match "manager/all"=>"manager#all"
  resources :girls
 
  post "girls/try"=>'girls#try'
  get "users/new"
  
  resources :boys

   match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
 
        operating system: <span id="platform"></span>&nbsp;&nbsp;&nbsp;&nbsp;
        browser: <span id="broswer"></span>


app/views/layouts/_header.html.erb
<%= t('hello') %>

app/views/layouts/_menu.html.erb
<ul>

  <li id="repo-management" class="left-menu">
     <%= link_to upload_uploadin_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">入库表导入</div>
     <% end %>
     
     <%= link_to girls_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">出库表导入</div>
     <% end %>
     
     <%= link_to girls_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">出入库记录查询</div>
     <% end %>
     
     <%= link_to manager_all_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">物料查询</div>
     <% end %>
  </li>
  
  <li id="project-management" class="left-menu">
    
    <%= link_to code_list_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_12.png", :class=>'menu-icon') %></div>
     <div class="menu-text">用户管理</div>
     <% end %>
    
     <%= link_to new_boy_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">用户管理</div>
     <% end %>
     
  </li>
  
  <li id="tree" class="left-menu">
 
  </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Codeapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <%= render :partial => "layouts/header" %>
</div>
<div id="menu">
  <%= render :partial => "layouts/menu" %>
</div>
<div id="footer">
  <%= render :partial => "layouts/footer" %>
</div>
<div id="home-page">
<%= yield %></div>
</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Extapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<div id="ajax">ajax</div>
</html>